

import React from "react";

export const metadata = {
  title: "Terms & Conditions",
  description: "Accsysindia Terms and Conditions"
};

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto p-6 bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100">
      <h1 className="text-3xl font-bold mb-6 text-center">Terms &amp; Conditions</h1>
      <div className="prose prose-lg dark:prose-invert space-y-4">
        <p>Access to and use of www.accsysindia.com website (hereinafter the accsysindia Website) and the information, materials, products and services available through the accsysindia Website are subject to these terms of use (the Website Terms of Use).</p>
        <p>The Website Terms of Use may be updated from time to time. Updated versions will be posted on the Accsysindia Website and are effective immediately. When using the Accsysindia Website you should regularly verify whether the Website Terms of Use have been updated or amended. The accsysindia Website provides information on Accsysindia, the Accsysindia Business and accsysindia products and services, and is intended only for users from and in India.</p>
        <h2 className="text-2xl font-semibold mt-4">Password Protected Parts of the Accsysindia Website</h2>
        <p>The password-protected parts of the accsysindia Website are intended exclusively for users including accsysindia members in India. If you do not already know a accsysindia Member and wish to register, please use 'Find a Member' under 'Join accsysindia option' at www.accsysindia.com.</p>
        <p>Please note: Passwords should not be given to third parties and must be protected from unauthorized access. If you become aware of any unauthorized use of your password, you should notify accsysindia immediately. Accsysindia disclaims any liability and responsibility for damage caused as a result of improper use of passwords.</p>
        <h2 className="text-2xl font-semibold mt-4">Privacy Statement and Policies</h2>
        <p>All personal data provided to accsysindia while using the accsysindia Website will be handled in accordance with the Website Privacy Notice.</p>
        <p>All information provided to accsysindia during the use of the accsysindia Website must be correct, complete, and up to date. If we have reason to believe that incorrect, incomplete or outdated information has been provided, access to the accsysindia Website may be limited or blocked.</p>
        <h2 className="text-2xl font-semibold mt-4">Copyright and Use of accsysindia Website Materials</h2>
        <p>The accsysindia Website and materials made available on the accsysindia Website are protected by intellectual property rights, including copyrights, trade names and trademarks, including the name accsysindia and the accsysindia logo, and are owned by accsysindia or used by accsysindia under a license or with permission from the owner of such rights. Materials protected by such intellectual property rights include the design, layout, look, appearance, graphics, photos, images, articles, stories and other materials available on the accsysindia Website (collectively, Website Materials). Website Materials may only be reproduced, distributed, published or otherwise publicly presented based on a prior written consent by accsysindia. As an exception to this rule, accsysindia grants users a limited, non-exclusive, non-transferable, non-assignable, revocable license to use Website Materials solely for the purposes of operating their accsysindia Members' business by downloading, storing, printing, copying, sharing and displaying Website Materials, provided that the Material is unaltered and the source of information is quoted in case any Website Materials are disclosed to third parties.</p>
        <p>The right to use the password-protected parts of the accsysindia Website as a accsysindia Member ends on termination of the Accsysindia Member Contract without the need for any further actions by accsysindia. For all other users, the right to use the password-protected parts of the accsysindia Website ends on termination of the contractual obligation of such user or at the discretion of accsysindia. In the event of termination thereof, the user must delete or destroy all stored, printed or copied materials, unless they must be retained to comply with legal requirements.</p>
        <h2 className="text-2xl font-semibold mt-4">Links to Other Websites</h2>
        <p>We may link to other Third- Party websites which are not within our control. We are not responsible or liable for the information or materials made available by such third-party websites. We encourage you to read the terms of use and privacy statements of all third-party websites before using such websites or submitting any personal data or any other information on or through such websites.</p>
        <h2 className="text-2xl font-semibold mt-4">Links from Other Websites to the Accsysindia Website</h2>
        <p>Inserting links from a third-party website to www.accsysindia.com requires prior written consent from accsysindia. If you would like to link from other websites, please contact us through the Contact Form.</p>
        <h2 className="text-2xl font-semibold mt-4">Limitation of Liability, Disclaimer of Warranties and Indemnification</h2>
        <p>Accsysindia will not be liable for any delay or interruption in your access to the Website or any content located on the Website, or for any transmission errors, equipment or software incompatibilities, force majeure or other failure of performance.</p>
        <p>Accsysindia will use reasonable efforts to correct any failure of performance, but Accsysindia will not be required to make any changes to any equipment or software used by Accsysindia or its contractors or agents to ensure compatibility with any equipment or software used by you. You may not use the Website or the content on the site for any commercial purpose, including but not limited to the use of any of the content to market or sell goods or services to any person. You agree not to launch any automated system, including without limitation, "robots," "spiders," or "offline readers," to access the site.</p>
        <p>accsysindia will use reasonable efforts to ensure that the information and materials provided on this website are correct. You agree that your use of the site shall be at your sole risk, and accsysindia will not be held liable in any way for your use of the site or for any information contained on the site. All content contained in or referred to on the site is provided "as is" basis, without any representations or warranties, express or implied. To the fullest extent permitted by law, accsysindia disclaims all warranties, express or implied, including, without limitation, all implied warranties of merchantability and fitness for a particular purpose.</p>
        <p>accsysindia makes no warranties that the site will be errorfree, or that any errors will be corrected, or that the website or the server from which the site is operated will be free of viruses or other potentially harmful codes. Under no circumstances, including negligence, shall accsysindia be held liable for any direct, indirect, incidental, special or consequential damages and expenses of any kind (including, without limitation, personal injury or property damage, lost profits, and damages arising from computer viruses, business interruption, lost data, unauthorized access to or use of site servers or any personal information stored therein, or any interruption or cessation of operation of the website) arising out of or in any way connected with the use of the website or any information contained on the site, whether such damages are based on contract, tort, strict liability or otherwise, even if advised of the possibility of such damages.</p>
        <p>You agree to indemnify, defend and hold accsysindia and its affiliates harmless from any liability or loss, related to either your violation of these website terms of use or your use of the accsysindia website.</p>
        <h2 className="text-2xl font-semibold mt-4">Restricting or Blocking Access to the Accsysindia Website for Violations of the Website Terms of Use</h2>
        <p>In case of violation of these Website Terms of Use, particularly in case of use of the Accsysindia Website or individual elements of the Accsysindia Website for other than its intended use, access to the Accsysindia Website may be restricted or blocked. Accsysindia generally reserves the right to partially or entirely alter, block, or discontinue the Accsysindia Website or its content at any time and for any reason.</p>
        <h2 className="text-2xl font-semibold mt-4">Severability Clause</h2>
        <p>Should one of the provisions of these Website Terms of Use be invalid or declared invalid by a court, this will not affect the validity of the remaining terms.</p>
        <h2 className="text-2xl font-semibold mt-4">Choice of law, Jurisdiction and Venue</h2>
        <p>The use of the accsysindia Website and these Website Terms of Use are governed by the laws of India. The courts of New Delhi have exclusive jurisdiction and venue for any disputes arising from or in connection with the use of the accsysindia Website or these Website Terms of Use.</p>
        <h2 className="text-2xl font-semibold mt-4">Notice</h2>
        <p>If you have any comments or inquiries about these Terms of use, if you would like to update information we have about you, or to exercise your rights, you may contact our Call Centre at 080-69050505, or on <a href="mailto:custormercare@accsysindia.com" className="text-primary underline">custormercare@accsysindia.com</a>.</p>
      </div>
    </div>
  );
}
